schema_version: 1

context:
  version: "0.5.0"

package:
  name: macroverse
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/m/macroverse/macroverse-${{ version }}.tar.gz
    sha256: a86f035a2f749a515dc22b29fd312d9c5b4c7721eb30debde5b3da8daf87beea

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - macroverse = macroverse.cli:app

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build
    - pip
  run:
    - python >=${{ python_min }}
    - jupyverse >=0.11.1,<0.12.0
    - fps-jupyterlab >=0.10.5,<0.11.0
    - fps-auth >=0.9.3,<0.10.0
    - fps-login >=0.9.3,<0.10.0
    - cyclopts >=4.4.3,<5.0.0
    - holm >=0.7.4
    - pyyaml >=6.0.3,<7.0.0
    - httpx >=0.28.1,<1.0.0
    - structlog
    - psutil
    - types-psutil
    - types-PyYAML
    - nginx

tests:
  - python:
      imports:
        - macroverse
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - macroverse --help

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/davidbrochart/macroverse
  summary: Jupyverse deployment.

extra:
  recipe-maintainers:
    - davidbrochart
