schema_version: 1

context:
  version: "0.5.0"

package:
  name: macroverse
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/m/macroverse/macroverse-${{ version }}.tar.gz
    sha256: a86f035a2f749a515dc22b29fd312d9c5b4c7721eb30debde5b3da8daf87beea

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - macroverse = macroverse.cli:app

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build
    - pip
  run:
    - python >=${{ python_min }}
    - fps >=0.5.8,<0.6.0
    - fastapi
    - anycorn >=0.18.1,<0.19.0
    - fps-auth
    - fps-login
    - fps-jupyterlab
    - fps-contents
    - fps-file-id
    - fps-file-watcher
    - fps-nbconvert
    - fps-yjs
    - fps-lab
    - fps-frontend
    - jupyverse-api
    - cyclopts >=4.4.3,<5.0.0
    - holm >=0.8.1
    - pyyaml >=6.0.3,<7.0.0
    - httpx >=0.28.1,<1.0.0
    - structlog
    - psutil
    - types-psutil
    - types-PyYAML
    - nginx

tests:
  - python:
      imports:
        - macroverse
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - macroverse --help

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/davidbrochart/macroverse
  summary: Jupyverse environment deployment.

extra:
  recipe-maintainers:
    - davidbrochart
